config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/contact'
  get 'pages/what'
  get 'pages/colusion'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def contact
  end
  def what
  end
  def colusion
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SevenLukas</title>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script
    src="http://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>


    <script src="<%= asset_path 'imagesloaded.pkgd.min.js' %>" charset="utf-8"></script>
    <script src="<%= asset_path 'masonry.pkgd.min.js' %>" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script src="<%= asset_path 'color-thief.min.js' %>" charset="utf-8"></script>
    <script src="<%= asset_path 'galleryExpand.js' %>" charset="utf-8"></script>
    <script src="<%= asset_path 'init.js' %>" charset="utf-8"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $('select').formSelect();
        $('.tooltipped').tooltip();
      });
    </script>
  </body>
</html>

app/views/pages/colusion.html.erb
<nav class="nav-extended nav-full-header teal lighten-2" id="other_nav">
  <div class="nav-wrapper container">
    <a href="<%= root_path %>" class="brand-logo" ><%= image_tag 'confort millonario.png', id: 'loguito' %> <span id="marca">Seven Lukas</span></a>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="<%= pages_what_path %>">¿Qué es esto?</a></li>
      <li><a href="<%= pages_colusion_path %>">Colusión</a></li>
      <li><a href="<%= pages_contact_path %>">Contacto</a></li>
    </ul>
  </div>
  </nav>

app/views/pages/contact.html.erb
<nav class="nav-extended nav-full-header teal lighten-2" id="other_nav">
  <div class="nav-wrapper container">
    <a href="<%= root_path %>" class="brand-logo" ><%= image_tag 'confort millonario.png', id: 'loguito' %> <span id="marca">Seven Lukas</span></a>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="<%= pages_what_path %>">¿Qué es esto?</a></li>
      <li><a href="<%= pages_colusion_path %>">Colusión</a></li>
      <li><a href="<%= pages_contact_path %>">Contacto</a></li>
    </ul>
  </div>
  </nav>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
<div class="container">
  <div class="row">

      <form class="col s12" action="https://formspree.io/lucas.otarola@gmail.com"
      method="POST">
        <div class="row">
          <div class="input-field col s6">
            <input id="last_name" type="text" class="validate" name="nombre_tienda">
            <label for="last_name">Nombre de la tienda</label>
          </div>

          <div class="input-field col s6">
            <input id="last_name" type="text" class="validate" name="email">
            <label for="last_name">Email</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s6">
            <select>
              <option value="" disabled selected>Elige la categoría de tu tienda</option>
              <option value="Tecnología">Tecnología</option>
              <option value="Belleza">Belleza</option>
              <option value="Ropa">Ropa</option>
              <option value="Mascotas">Mascotas</option>
              <option value="Cuentas">Cuentas Premium</option>
              <option value="JuegosVideo">Video Juegos</option>
              <option value="Cupones">Cuponeras</option>
              <option value="Celulares">Celulares</option>
              <option value="Otros">Otros</option>
            </select>
            <label>Categoria</label>
          </div>
          <div class="col s6">
            <i class="material-icons">info_outline</i><br>
            Si tu categoría no está, incluyelo en el mensaje.
          </div>
        </div>

        <div class="row">
          <br>
          <div class="input-field col s6">
            <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
            <label for="icon_prefix2">Mensaje</label>
          </div>

        </div>
        <div class="row">
          <div class="col s6">
            <input type="submit" class="btn btn-primary">
          </div>
        </div>
        </div>
      </form>
    </div>
</div>

app/views/pages/what.html.erb
<nav class="nav-extended nav-full-header teal lighten-2" id="other_nav">
  <div class="nav-wrapper container">
    <a href="<%= root_path %>" class="brand-logo" ><%= image_tag 'confort millonario.png', id: 'loguito' %> <span id="marca">Seven Lukas</span></a>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="<%= pages_what_path %>">¿Qué es esto?</a></li>
      <li><a href="<%= pages_colusion_path %>">Colusión</a></li>
      <li><a href="<%= pages_contact_path %>">Contacto</a></li>
    </ul>
  </div>
  </nav>